[BE-#13] OAuth 인증 관련 기능 개발
codesquad-member-2020/issue-tracker-01 pull request #34
Opened 2020-06-11 12:04 UTC by haveagood

Fixes #13

## 설명
- Github OAuth Login 기능을 개발하였습니다.
- Github에서 User정보를 받아와서 nickname, email을 jwt 토큰으로 저장하여 token을 cookie로 전달하도록 하였습니다.
- User정보를 저장하는 기능은 미구현 상태입니다.(JPA 연동 미구현)

## 작업 유형

- [ ] 신규 기능 추가
- [ ] 버그 수정
- [ ] 관련 문서 업데이트 필요

## 체크리스트

- [ ] 이 PR의 코드들이 이 프로젝트의 스타일 가이드를 준수했는가?
- [ ] 내 코드에 대한 자기 검토가 되었는가?
- [ ] 이해하기 힘든 부분의 코드에 주석이 작성되었는가?
- [ ] 변경사항에 대한 문서를 작성하였는가?
- [ ] 변경사항이 새로운 경고를 만들어내지 않았는가?
- [ ] 변경사항이 효과적이거나 동작이 작동한다는 것을 보증하는 테스트를 추가하였는가?
- [ ] 새로운 테스트와 기존의 테스트가 변경사항에 대해 만족하는가?

2020-06-11 12:39 UTC, ksundong commented on .idea/workspace.xml
> +</project>
@haveagood 
이 파일 커밋에 포함되면 안될 것 같은데 확인 한 번 부탁드려요~

2020-06-11 12:39 UTC, ksundong commented on BE/.gitignore
> +application-secret.properties
secret property가 추가되었군요..!
이런 정보는 공유 부탁드릴게요!!

2020-06-11 12:39 UTC, ksundong commented on BE/build.gradle
> -    implementation 'org.springframework.boot:spring-boot-starter-data-elasticsearch'
앗 이거 왜 빼셨을까요?
없어도 동작은 되지 않나요??

2020-06-11 12:39 UTC, ksundong commented on .idea/workspace.xml
> +</project>
이 파일 커밋에 포함되면 안될 것 같은데 확인 부탁드릴게요!

2020-06-11 12:39 UTC, ksundong commented on BE/.gitignore
> +application-secret.properties
앗 secret.properties라는게 추가되었군요.

2020-06-11 12:39 UTC, ksundong commented on BE/build.gradle
> -    implementation 'org.springframework.boot:spring-boot-starter-data-elasticsearch'
이 의존성 있어도 동작은 하지 않나요? 왜 빼셨는지 궁금하네요!

2020-06-11 12:40 UTC, ksundong commented on BE/src/main/java/kr/codesquad/issuetracker/common/exception/ErrorCode.java
> +package kr.codesquad.issuetracker.common.exception;
앗 예전하고 패키징이 달라졌네요.
Exception Class와 같이 있으면 단점은 없을까요??

추후에 Exception Class들이 많아지는 경우가 있었어요. 그 경우에 분리를 하면 될까요?

2020-06-11 12:41 UTC, ksundong commented on BE/src/main/java/kr/codesquad/issuetracker/common/exception/ErrorCode.java
> +@Getter
Getter를 통해 생성해주는군요. 좋습니다!

2020-06-11 12:42 UTC, ksundong commented on BE/src/main/java/kr/codesquad/issuetracker/common/security/GithubKey.java
> +    }
`@AllArgsConstructor` 를 사용하면 더 깔끔해지겠네요.

2020-06-11 12:46 UTC, ksundong commented on BE/src/main/java/kr/codesquad/issuetracker/common/security/GithubKey.java
> +    private final String clientId;
```suggestion
public class GithubKey {

    private final String clientId;
```

2020-06-11 12:46 UTC, ksundong commented on BE/src/main/java/kr/codesquad/issuetracker/common/security/GithubKey.java
> +    private final String clientId;
코딩 컨벤션이 클래스 다음에 빈 라인을 추가하는 것 같아 변경 요청드립니다!

2020-06-11 12:48 UTC, ksundong commented on BE/src/main/java/kr/codesquad/issuetracker/controller/LoginController.java
> +@RequestMapping("/login")
저는 `@RestController` 같이 중요한 Bean을 가장 class와 가깝게 두는데 어떻게 생각하시는지 궁금합니다!

2020-06-11 12:49 UTC, ksundong commented on BE/src/main/java/kr/codesquad/issuetracker/controller/LoginController.java
> +    private static final Logger log = LoggerFactory.getLogger(LoginController.class);
`@Slf4j` 를 사용하면 되겠네요~

2020-06-11 12:50 UTC, ksundong commented on BE/src/main/java/kr/codesquad/issuetracker/controller/LoginController.java
> +    }
`@RequireArgsConstructor`를 사용하면 되겠네요~

2020-06-11 12:53 UTC, ksundong commented on BE/src/main/java/kr/codesquad/issuetracker/controller/LoginController.java
> +        log.info("user data : {}", user.toString());
```suggestion
        log.info("user data : {}", user);
```

2020-06-11 12:54 UTC, ksundong commented on BE/src/main/java/kr/codesquad/issuetracker/controller/LoginController.java
> +        UserDTO user = loginService.createUserDTO(savedUser);
```suggestion
        UserDTO user = UserDTO.of(loginService.insertUser(accessToken));
```

그냥 UserDTO.of(savedUser)를 써도 되는 부분 아닌가요?
Service Layer에 굳이 올라가야 할 이유를 모르겠습니다~

2020-06-11 12:55 UTC, ksundong commented on BE/src/main/java/kr/codesquad/issuetracker/domain/User.java
> -
요기 빈 라인은 다시 넣어주세요!

2020-06-11 12:56 UTC, ksundong commented on BE/src/main/java/kr/codesquad/issuetracker/domain/User.java
> +    public User(Long id, String userId, String email, String nickname, String githubToken, String profileImage) {
private으로 다시 바꿔주세요!

2020-06-11 12:56 UTC, ksundong commented on BE/src/main/java/kr/codesquad/issuetracker/domain/UserDTO.java
> +package kr.codesquad.issuetracker.domain;
DTO가 domain하고 같이 패키징 되면 안될 것 같다고 생각하는데, Alex 생각은 어떠세요?

2020-06-11 13:00 UTC, ksundong commented on BE/src/main/java/kr/codesquad/issuetracker/domain/UserDTO.java
> +    }
```suggestion

    public static UserDTO of(String nickname, String email) {
        return new UserDTO(nickname, email);
    }

    public static UserDTO of(Map<String, String> userMap) {
        return new UserDTO(userMap.get("nickname"), userMap.get("email"));
    }

    public static UserDTO of(User user) {
        return new UserDTO(user.getNickname(), user.getEmail());
    }
```

그리고 User 객체 자체를 넘겨받아 DTO를 만들어주는 메소드도 필요하다고 생각합니다~
좀 더 객체지향적인 접근을 하는 것이 좋을 듯 해요!

2020-06-11 13:01 UTC, ksundong commented on BE/src/main/java/kr/codesquad/issuetracker/service/JwtService.java
> +    private static final Logger log = LoggerFactory.getLogger(JwtService.class);
logger는 `@Slf4j` 사용해주세요!

2020-06-11 13:09 UTC, ksundong commented on BE/src/main/java/kr/codesquad/issuetracker/service/JwtService.java
> +            throw new LoginRequiredException("인증되지 않은 jwt token입니다.");
이건 새로운 Exception을 만드는게 좋을 것 같네요~

2020-06-11 13:10 UTC, ksundong commented on BE/src/main/java/kr/codesquad/issuetracker/service/JwtService.java
> +            // Custom Exception Unauthorized Exception
이 주석의 의미는 뭘까요?

2020-06-11 13:11 UTC, ksundong commented on BE/src/main/java/kr/codesquad/issuetracker/service/LoginService.java
> +    private static final Logger log = LoggerFactory.getLogger(LoginService.class);
`@Slf4j` 어노테이션 사용해주세요!

2020-06-11 13:11 UTC, ksundong commented on BE/src/main/java/kr/codesquad/issuetracker/service/LoginService.java
> +    private String GITHUB_CLIENT_ID;
네이밍 컨벤션 지켜주세요~

2020-06-11 13:12 UTC, ksundong commented on BE/src/main/java/kr/codesquad/issuetracker/service/LoginService.java
> +    private static int MAX_AGE = 7 * 24 * 60 * 60;
final 을 붙여주는 편이 더 좋지않을까요?
네이밍 컨벤션에도 맞지 않습니다!

2020-06-11 13:12 UTC, ksundong commented on BE/src/main/java/kr/codesquad/issuetracker/service/LoginService.java
> +    @Value("${GITHUB_CLIENT_ID}")
```suggestion
    private final OAuthService authService;

    @Value("${GITHUB_CLIENT_ID}")
```

2020-06-11 13:13 UTC, ksundong commented on BE/src/main/java/kr/codesquad/issuetracker/service/LoginService.java
> +    }
`@RequireArgsConstructor`를 사용하는게 좋을 것 같습니다!

2020-06-11 13:13 UTC, ksundong commented on BE/src/main/java/kr/codesquad/issuetracker/service/LoginService.java
> +        URI uri = UriComponentsBuilder.fromUriString("https://github.com/login/oauth/authorize")
하드코딩을 따로 빼는 것도 좋을 듯 합니다!

2020-06-11 13:14 UTC, ksundong commented on BE/src/main/java/kr/codesquad/issuetracker/service/LoginService.java
> +        return headers;
이게 아마 한이 작성했던 코드일텐데, 하드코딩이 너무 많아져서 지양하고 싶은 방식이었습니다!
딱히 바꾸실 생각이 없었던 것 같은데, 이 부분은 제가 다시 생각을 해보도록 할게요!

2020-06-11 13:15 UTC, ksundong commented on BE/src/main/java/kr/codesquad/issuetracker/service/LoginService.java
> +        log.info("User Info : {}", user);
왜 info로 로깅을 하는지 궁금하네요!

2020-06-11 13:15 UTC, ksundong commented on BE/src/main/java/kr/codesquad/issuetracker/service/LoginService.java
> +    @Transactional
왜 Transactional이 쓰였을까요?

2020-06-11 13:16 UTC, ksundong commented on BE/src/main/java/kr/codesquad/issuetracker/service/LoginService.java
> +    }
```suggestion
```

2020-06-11 13:16 UTC, ksundong commented on BE/src/main/java/kr/codesquad/issuetracker/service/LoginService.java
> +        headers.setLocation(URI.create("http://localhost:8080"));
😅 localhost가 박혀있으면 배포가 되었을 때 어떻게 될까요?

2020-06-11 13:17 UTC, ksundong commented on BE/src/main/java/kr/codesquad/issuetracker/service/LoginService.java
> +        headers.setLocation(URI.create("http://localhost:8080"));
역시 이 부분도 한이 개발한 방식인데 제가 좀 더 고민해볼게요.
저는 일단 Cookie 클래스를 사용하는게 더 낫다고 생각하는 입장이에요!

2020-06-11 13:18 UTC, ksundong commented on BE/src/main/java/kr/codesquad/issuetracker/service/OAuthService.java
> +    private static final String GITHUB_USER_API_URL = "https://api.github.com/user";
```suggestion
public class OAuthService {

    private static final String GITHUB_ACCESS_TOKEN_URL = "https://github.com/login/oauth/access_token";
    private static final String GITHUB_USER_API_URL = "https://api.github.com/user";
```

2020-06-11 13:18 UTC, ksundong commented on BE/src/main/java/kr/codesquad/issuetracker/service/OAuthService.java
> +    private String GITHUB_CLIENT_SECRET;
네이밍 컨벤션 지켜주세요~

2020-06-11 13:18 UTC, ksundong commented on BE/src/main/java/kr/codesquad/issuetracker/service/OAuthService.java
> +    private static final Logger log = LoggerFactory.getLogger(OAuthService.class);
`@Slf4j` 써주세요~

2020-06-11 13:19 UTC, ksundong commented on BE/src/main/java/kr/codesquad/issuetracker/service/OAuthService.java
> +                GithubPayload.of(new GithubKey(GITHUB_CLIENT_ID, GITHUB_CLIENT_SECRET), code));
차라리 GithubKey를 Bean 등록해서 가져다 쓰는 방식이 훨씬 나을 것 같네요.
좀 어려운가요?

2020-06-11 13:20 UTC, ksundong commented on BE/src/main/java/kr/codesquad/issuetracker/service/OAuthService.java
> +                        .getBody())
이 부분을 별도의 Service로 빼는 것도 고민해볼만 하네요!

2020-06-11 13:20 UTC, ksundong commented on BE/src/main/java/kr/codesquad/issuetracker/service/OAuthService.java
> +        log.info("user info from github: {}", user);
여기도 info로 로깅을 하네요? 왤까요?

2020-06-11 13:20 UTC, ksundong commented on BE/src/main/java/kr/codesquad/issuetracker/service/OAuthService.java
> +        String eamil = new RestTemplate()
오타 있습니다! email이에요!

2020-06-11 13:21 UTC, ksundong commented on BE/src/main/java/kr/codesquad/issuetracker/service/OAuthService.java
> +        log.info("email info : {}", eamil);
여기도 info 로깅이네요!

2020-06-11 13:22 UTC, ksundong requested changes
코드 잘 봤습니다!

이전에 Han 코드가 제 기준에 썩 만족스럽게 나오지 않아서 그런가 리뷰를 많이 남겼네요 ㅋㅋ
고생많으셨습니다!

2020-06-11 13:50 UTC, haveagood commented on BE/src/main/java/kr/codesquad/issuetracker/controller/LoginController.java
> +        log.info("user data : {}", user.toString());
오홍 이거 toString 안쓰면 객체 출력이 잘 되나요? 뭔가 객체 출력이 안되고, 암호화되어서 출력되는 느낌이라 일부로 toString 쓴건데

2020-06-11 13:53 UTC, ksundong commented on BE/src/main/java/kr/codesquad/issuetracker/controller/LoginController.java
> +        log.info("user data : {}", user.toString());
한 번 적용해보세요! 원래 차이가 없어야 정상입니다!

2020-06-11 14:33 UTC, haveagood commented on BE/src/main/java/kr/codesquad/issuetracker/service/LoginService.java
> +        headers.setLocation(URI.create("http://localhost:8080"));
현재 redirect를 localhost로 잡아놨는데 이건 차후에 변경해야 할 것 같습니당

2020-06-11 14:34 UTC, haveagood commented on BE/src/main/java/kr/codesquad/issuetracker/service/LoginService.java
> +        headers.setLocation(URI.create("http://localhost:8080"));
저도 쿠키로 개발을 하긴 했는데 고민좀 해보겠스빈다

2020-06-11 14:36 UTC, haveagood commented on BE/src/main/java/kr/codesquad/issuetracker/service/LoginService.java
> +        log.info("User Info : {}", user);
정보성 메세지는 info를 주로 쓴다고 검색해서 봤던 기억때문에 저는 주로 info를 쓰는데 debug 단계로 낮추는게 나을까요?

2020-06-11 14:37 UTC, haveagood commented on BE/src/main/java/kr/codesquad/issuetracker/domain/UserDTO.java
> +    }
이거는 위에부분 수정하면서 만들었습니당 ㅋㅋ

2020-06-11 14:38 UTC, haveagood commented on BE/src/main/java/kr/codesquad/issuetracker/service/JwtService.java
> +    private static final Logger log = LoggerFactory.getLogger(JwtService.class);
오호 어노테이션이 있군요

2020-06-11 14:40 UTC, haveagood commented on BE/src/main/java/kr/codesquad/issuetracker/domain/UserDTO.java
> +package kr.codesquad.issuetracker.domain;
DTO도 어떻게보면 Domain모델의 일종이 아닐까요?
Entitiy가 domain이라고 알고 있는데, 비슷한 개념이라 일단 생각을 했습니다.

2020-06-11 14:40 UTC, haveagood commented on BE/src/main/java/kr/codesquad/issuetracker/domain/UserDTO.java
> +package kr.codesquad.issuetracker.domain;
일단 조금 더 검색을 해봐야겠네요

2020-06-11 14:44 UTC, haveagood commented on BE/src/main/java/kr/codesquad/issuetracker/service/OAuthService.java
> +                GithubPayload.of(new GithubKey(GITHUB_CLIENT_ID, GITHUB_CLIENT_SECRET), code));
일단 처음 개발은 Bean등록해서 사용했는데, 리뷰에서 지적받은 내용이라고 들어서 수정했거든요 일단, Bean으로 되돌리도록 하겠습니다.

2020-06-11 15:46 UTC, ksundong commented on BE/src/main/java/kr/codesquad/issuetracker/service/LoginService.java
> +        log.info("User Info : {}", user);
info는 꽤나 높은 레벨의 로깅입니다! 꼭 필요한 정보인가요??
필요하다면 info level로 지정해주는게 좋을 듯 합니다!

근데 전반적으로 info logging이 많다고 느꼈어요!

2020-06-11 15:46 UTC, ksundong commented on BE/src/main/java/kr/codesquad/issuetracker/service/OAuthService.java
> +                GithubPayload.of(new GithubKey(GITHUB_CLIENT_ID, GITHUB_CLIENT_SECRET), code));
앗 그런가요? 제가 그렇게 말을했었나...
내일 다시 얘기해보시죠!

2020-06-13 06:39 UTC, wheejuni commented on .idea/workspace.xml
> +</project>
이게 포함되는 것의 장단점이 있는데...
포함된다면 일단 IDE가 이 파일을 인식해서 작업창을 구성해주기 때문에, 팀원들이 힘들이지 않고도 작업 환경을 공유할 수 있는 이점이 있습니다. 뭐 Datasource 설정이라던지 기타 필요한 정보 같은 것들이요.

사실 이게 뭐 그렇게 대수냐 할 수도 있지만 코드가 비대한 조직에서는 새 소스를 내려받고 작업 환경 구축하기까지의 삽질도 엄청나게 많이 필요한 상황을 많이 봤습니다. 

그래서 이 파일을 트래킹에 넣을 것인지 말 것인지를 판단하는건... 장단점을 잘 살펴보시고 협업자들끼리 결정했으면 좋겠네요. 무조건 빼고 넣고 할 문제는 아닙니다.

2020-06-13 14:20 UTC, ksundong commented on .idea/workspace.xml
> +</project>
@wheejuni 이 파일이 현재 gitignore에 등록이 되어있는데, 커밋에 포함되어서 리뷰를 달았어요!

말씀하신 내용은 검색을 통해서 더 알게되었네요.
https://intellij-support.jetbrains.com/hc/en-us/articles/206544839

그리고 저희끼리 얘기하기론 올리지 않아야 되는거 아니냐는 얘기가 나왔어서 리뷰를 남겼었어요!

제걸 보고 Alex의 workspace.xml을 보니까 제 workspace.xml이 더 크네요 -0- 여기서 커밋 남긴 이력도 다 기록하는 것 같습니다.

2020-06-14 08:00 UTC, ksundong commented
테스트

2020-06-14 08:00 UTC, ksundong commented
Can one of the admins verify this patch?

2020-06-15 08:33 UTC, ksundong commented
테스트

2020-06-15 08:34 UTC, merged